Dcac 138 Add Authentication and Authorisation checks.
companieshouse/document-signing-api pull request #19
Opened 2023-03-17 11:57 UTC by mcolwellch

Resolves: DCAC-138

Added authentication and authorisation for internal API users to use the application.

2023-03-28 16:46 UTC, caismith-ch commented on src/main/java/uk/gov/companieshouse/documentsigningapi/interceptor/UserAuthorisationInterceptor.java
> +        //
Please remove this comment.

2023-03-28 16:47 UTC, caismith-ch commented on src/test/java/uk/gov/companieshouse/documentsigningapi/controller/SignDocumentControllerIntegrationTest.java
> +//
Remove these commented out lines.

2023-03-28 16:48 UTC, caismith-ch commented on src/test/java/uk/gov/companieshouse/documentsigningapi/controller/SignDocumentControllerTest.java
> +import static uk.gov.companieshouse.documentsigningapi.util.TestConstants.*;
Its best practice to not use the wildcard in imports and instead import only what you need. It may be a setting in you IDE .

2023-03-28 16:48 UTC, caismith-ch commented on src/test/java/uk/gov/companieshouse/documentsigningapi/controller/SignDocumentControllerTest.java
> +import static org.mockito.Mockito.*;
Its best practice to not use the wildcard in imports and instead import only what you need. It may be a setting in you IDE .

2023-03-28 16:49 UTC, caismith-ch commented on src/test/java/uk/gov/companieshouse/documentsigningapi/interceptor/UserAuthorisationInterceptorTest.java
> +    void willNotAuthorise_IfEricHeadersPresentAndIncorrectValue() throws Exception {
Remove underscore from method name.

2023-03-28 16:49 UTC, caismith-ch commented
The `main` branch will need to be merged into this branch to fix the conflicts.

2023-03-29 05:09 UTC, hwilliams1 requested changes
Couple of comments on indentation and code re-use

2023-03-29 05:09 UTC, hwilliams1 commented on src/test/java/uk/gov/companieshouse/documentsigningapi/controller/SignDocumentControllerIntegrationTest.java
> +                        .header(ERIC_AUTHORIZED_KEY_ROLES, ERIC_AUTHORIZED_KEY_ROLES_VALUE)
The indentation on these lines appears to differ from lines 172-174, can it be consistent throughout please?

2023-03-29 05:09 UTC, hwilliams1 commented on src/test/java/uk/gov/companieshouse/documentsigningapi/controller/SignDocumentControllerIntegrationTest.java
> +                        .header(ERIC_AUTHORIZED_KEY_ROLES, ERIC_AUTHORIZED_KEY_ROLES_VALUE)
The indentation on these lines appears to differ from lines 172-174, can it be consistent throughout please?

2023-03-29 05:09 UTC, hwilliams1 commented on src/test/java/uk/gov/companieshouse/documentsigningapi/controller/SignDocumentControllerTest.java
> +        lenient().doReturn(ERIC_AUTHORIZED_KEY_ROLES_VALUE).when(request).getHeader(ERIC_AUTHORIZED_KEY_ROLES );
This appears to duplicate the lines 135-137? It could be extracted into a method to reduce/prevent code duplication

2023-03-29 07:28 UTC, VaughanJackson123 commented on src/main/java/uk/gov/companieshouse/documentsigningapi/interceptor/UserAuthenticationInterceptor.java
> +        final String identityType = EricHeaderHelper.getIdentityType(request);
I know we often end up with a mixture of `final` and non-`final` variables as our code evolves with different styles, but with new code we can be consistent in either using `final` where we know something should not change, or just not bother with using `final` at all (except in "constants") if we don't believe it adds value? 

Not a big deal.

2023-03-29 15:05 UTC, VaughanJackson123 approved these changes

2023-03-30 09:38 UTC, caismith-ch approved these changes

2023-03-30 09:43 UTC, merged